openapi: 3.0.3
info:
  version: 1.0.0
  title: Provincias API
  description: Provincias api 
  x-sla:
    $ref: ./plans.yaml
security:
  - BearerAuth: []
paths:
  /api/v1/provincias:
    x-router-controller: agroclimaticasController
    get:
      description: Returns all provincias
      operationId: getProvincias
      responses:
        200:
          description: Provincias list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/provincias'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    provincias:
        type: object
        required:
          - id
        properties:
          id:
            type: number
          name:
            type: string
          code:
            type: string
          country:
            type: string
          founded:
            type: number
          national:
            type: boolean
          logo:
            type: string
    error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
      additionalProperties: true